# Generated by Django 3.2.3 on 2021-05-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_person_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('feito', models.BooleanField(default=False)),
                ('criado', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
