# Generated by Django 3.2 on 2021-04-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_person_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='salary',
            new_name='salario',
        ),
    ]
