# Generated by Django 3.2 on 2021-04-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_rename_salario_person_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='salary',
            new_name='salario',
        ),
    ]
