# Generated by Django 3.2 on 2021-04-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_rename_salary_person_salario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='idade',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='sobrenome',
        ),
    ]
