# Generated by Django 3.2 on 2021-04-29 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20210422_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.person'),
        ),
    ]
